In [35]:
from sensor.utils.main_utils import read_yaml_file

In [36]:
pip install dill

Note: you may need to restart the kernel to use updated packages.


In [37]:
pip install PyYAML

Note: you may need to restart the kernel to use updated packages.


In [38]:
file_path="/Users/myhome/Downloads/mysensor/config/schema.yaml"

In [39]:
schema_config = read_yaml_file(file_path=file_path)

In [40]:
len(schema_config["columns"])

164

In [44]:
from sensor.components.data_validation import DataValidation 
from sensor.entity.config_entity import TrainingPipelineConfig,DataIngestionConfig,DataValidationConfig
from sensor.entity.artifact_entity import DataIngestionArtifact, DataValidationArtifact


In [45]:
from sensor.components.data_ingestion import DataIngestion

# Create an instance of DataIngestion
data_validation_instance = DataIngestion()

# Call the initiate_data_validation method
data_validation_artifact = data_validation_instance.initiate_data_validation()

# Access the train_dataframe from the DataValidationArtifact
train_dataframe = data_validation_artifact.train_dataframe

# Now you can use train_dataframe in your IPython notebook
print(train_dataframe.head())


TypeError: __init__() missing 1 required positional argument: 'data_ingestion_config'

In [33]:

len(schema_config["columns"])==len(train_dataframe.columns)

NameError: name 'schema_config' is not defined

In [46]:
from scipy.stats import ks_2samp

In [47]:
import numpy as np

In [48]:
d1 = np.arange(10)
d2 = np.arange(10)

In [9]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
test = ks_2samp(d1,d2)
test

KstestResult(statistic=0.0, pvalue=1.0, statistic_location=0, statistic_sign=1)

In [50]:
d1 = np.arange(10)
d2 = np.arange(100)

In [51]:
test = ks_2samp(d1,d2)
test

KstestResult(statistic=0.9, pvalue=7.88295587183084e-09, statistic_location=9, statistic_sign=1)

In [14]:
round(test.pvalue)

1

In [18]:
traing_file_path = "/Users/myhome/Downloads/mysensor/artifact/04_16_2024_07_19_48/data_ingestion/ingested/train.csv"

In [19]:
test_file_path ="/Users/myhome/Downloads/mysensor/artifact/04_16_2024_07_19_48/data_ingestion/ingested/test.csv"

In [20]:
import pandas as pd

In [21]:
train_df = pd.read_csv(traing_file_path)
test_df = pd.read_csv(test_file_path)

In [22]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [23]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [24]:
d1 = train_df['class']
d2  = test_df['class']
ks_2samp(d1,d2)

KstestResult(statistic=0.0003473129964145505, pvalue=1.0, statistic_location='neg', statistic_sign=-1)

In [28]:
from sensor.utils.main_utils import write_yaml_file

Reading .env file


In [25]:
def get_drift_report(base_df,current_df,threshold=0.05):
    report ={}
    for column in base_df.columns:
        d1 = base_df[column]
        d2  = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found=False
        else:
            is_found = True 
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            
            }})
    return report


In [27]:
drift_report = get_drift_report(train_df,test_df)
drift_report

{'class': {'p_value': 1.0, 'drift_status': False},
 'aa_000': {'p_value': 0.9770767521962898, 'drift_status': False},
 'ab_000': {'p_value': 0.9995278120687102, 'drift_status': False},
 'ac_000': {'p_value': 0.812701391110423, 'drift_status': False},
 'ad_000': {'p_value': 0.9576217949973966, 'drift_status': False},
 'ae_000': {'p_value': 0.9999795998303717, 'drift_status': False},
 'af_000': {'p_value': 0.9999995886971963, 'drift_status': False},
 'ag_000': {'p_value': 1.0, 'drift_status': False},
 'ag_001': {'p_value': 1.0, 'drift_status': False},
 'ag_002': {'p_value': 0.9761982399921855, 'drift_status': False},
 'ag_003': {'p_value': 0.8950778770339063, 'drift_status': False},
 'ag_004': {'p_value': 0.44275176013554196, 'drift_status': False},
 'ag_005': {'p_value': 0.9602887358203891, 'drift_status': False},
 'ag_006': {'p_value': 0.7724383255866087, 'drift_status': False},
 'ag_007': {'p_value': 0.8815246868573805, 'drift_status': False},
 'ag_008': {'p_value': 0.9960565936277189

In [29]:
import os
write_yaml_file(file_path=os.path.join(os.getcwd(),"report.yaml"),content=drift_report,replace=True)

In [2]:
from sensor.ml.model.estimator import TargetValueMapping

In [4]:
TargetValueMapping().to_dict()

{'neg': 0, 'pos': 1}

In [5]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}

In [2]:


#This is a dictionary parsing code written by Amit Jadhav 
#Because of an Indentation Error you will experience Attribute Error
 
class dict_parsing:
     
    def __init__(self,a):
        self.a = a
         
    def getkeys(self):
        if self.notdict():
            return list(self.a.keys())
            
    def getvalues(self):
        if self.notdict():
            return list(self.a.values())
            
    def notdict(self):
        if type(self.a) != dict:
            raise Exception(self,a,'not a dictionary')
        return 1
        
    def userinput(self):
        self.a = eval(input())
        print(self.a,type(self.a))
        print(self.getykeys())
        print(self.getvalyes())
        
    def insertion(self,k,v):
        self.a[k]=v
   
d = dict_parsing({"k1":"amit", "k2":[1,2,3,4,5]})
 
d.getkeys()


SyntaxError: invalid syntax (2779155913.py, line 33)

In [3]:
import numpy as np

# Training data array: 5 samples with 3 features and 1 label
train_arr = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 0],
    [10, 11, 12, 1],
    [13, 14, 15, 0]
])




In [5]:
x_train = train_arr[:, :-1]
# Output: array([[ 1,  2,  3],
#                [ 4,  5,  6],
#                [ 7,  8,  9],
#                [10, 11, 12],
#                [13, 14, 15]])
x_train

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [7]:
y_train = train_arr[:, -1]
# Output: array([0, 1, 0, 1, 0])
y_train

array([0, 1, 0, 1, 0])